#!/usr/bin/env python

from sys import argv
from os.path import split
from collections import defaultdict
from biom import Table

if len(argv) == 1:
    print "Usage: bl2biom <input-fp> <output-fp>"
    exit(1)

input_fp = argv[1]
output_fp = argv[2]

max_log_evalue = 1.0
minimum_pct_id = 0.55

def bl2biom(bl_lines, max_log_evalue, minimum_pct_id):
    # Thank you SO: http://stackoverflow.com/a/2600813/3424666
    data = defaultdict(lambda: defaultdict(int))
    observation_ids = set()
    query_id_field = 0
    subject_id_field = 1
    pct_id_field = 2
    evalue_field = 10
    for line in bl_lines:
        fields = line.split()
        if ((float(fields[evalue_field]) <= max_log_evalue) and
            (float(fields[pct_id_field]) / 100. >= minimum_pct_id)):
            sample_id, sequence_id = fields[query_id_field].split('_', 1)
            observation_id = fields[subject_id_field]
            data[sample_id][observation_id] += 1
            observation_ids.add(observation_id)

    return Table(data, sample_ids=data.keys(), observation_ids=observation_ids)

t = bl2biom(open(input_fp, 'U'), max_log_evalue, minimum_pct_id)

print t.delimited_self()
